#!/bin/bash
# Copyright © 2011-2013 Martin Ueding <dev@martin-ueding.de>

# Opens the current path in webbrowser on localhost webserver.

url="${PWD#"/home/mu/Branches/"}"

xdg-open "http://localhost/~mu/$url"
