#!/bin/bash
# Copyright (c) 2011-2012 Martin Ueding <dev@martin-ueding.de>

# opens the current path in webbrowser on localhost webserver

url="${PWD#"/home/mu/Branches/"}"

firefox "http://localhost/~mu/$url" & disown
