#!/bin/bash
# Copyright (c) 2011 Martin Ueding <dev@martin-ueding.de>

# opens the current path in webbrowser on localhost webserver

URL="${PWD#"/home/mu/Branches/"}"

firefox "http://localhost/~mu/$URL" & disown
